---
abstract: 'Facility for creating read-only scalars, arrays, hashes'
author:
  - 'Sanko Robinson <sanko@cpan.org> - http://sankorobinson.com/'
build_requires:
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Readonly
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Readonly:
    file: lib/Readonly.pm
    version: v1.500.0
  Readonly::Array:
    file: lib/Readonly.pm
    version: '1.05'
  Readonly::Hash:
    file: lib/Readonly.pm
    version: '1.05'
  Readonly::Scalar:
    file: lib/Readonly.pm
    version: '1.05'
recommends:
  perl: v5.20.0
requires:
  perl: v5.6.0
resources:
  bugtracker: https://github.com/sanko/readonly/issues
  homepage: https://github.com/sanko/readonly
  repository: https://github.com/sanko/readonly.git
version: v1.500.0
x_contributors:
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
